# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'traQ-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for traQ-iOS
  pod 'WebViewJavascriptBridge', '~> 6.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
